# Generated by Django 4.1.6 on 2023-04-01 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Useradd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(max_length=50)),
                ("last_name", models.TextField(max_length=50)),
                ("email", models.EmailField(max_length=250)),
                ("password", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
