# Generated by Django 4.1.6 on 2023-04-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useradd",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="useradd",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
