# Generated by Django 4.1.6 on 2023-04-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_rename_useradd_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
