# Generated by Django 4.1.6 on 2023-04-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_rename_user_user_add"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User_add",
        ),
    ]
